Handover memcached
container-images/memcached pull request #17
Opened 2018-11-09 11:51 UTC by phracek

Signed-off-by: Petr Stone Hracek <phracek@redhat.com>

This Pull Request prepares memcached container for handover under sclorg github organization.

2018-11-09 12:05 UTC, phracek commented
@pkubath and @hhorak please have a look on it before handover.

2018-11-12 12:11 UTC, pkubatrh requested changes
Please also move tests into `1.5/test` and create the files `1.5/.exclude-centos7` and `1.5/.exclude-rhel7`so that we ignore the OS version we do not build the image for.

2018-11-12 12:11 UTC, pkubatrh commented on Makefile
>  test: build
Please remove the `test` and `clean` rules as they are overriding the ones defined in common-container-scripts

2018-11-13 07:22 UTC, phracek commented on Makefile
>  test: build
@pkubatrh All your comments are fixed by the latest commit.

2018-11-13 08:44 UTC, pkubatrh commented
lgtm now, thanks!

2018-11-13 08:45 UTC, merged